name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    env:
      IMDB_TEST_KEY: ${{ secrets.IMDB_TEST_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} 
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }} 
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }} 
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: run pipeline
        run: |
          dvc repro

      - name: Run model tests
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        run: python scripts/promote_model.py

      - name: Run Flask app tests
        if: success()
        run: python -m unittest tests/test_flask_app.py

      - name: Configure AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          output-env-credentials: true

      - name: Login to AWS ECR
        if: success()
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
      - env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name: Build Docker image
      #   run: |
      #       docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      # - name: Tag Docker image
      #   run: |
      #       docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
      #       ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    
      # - name: Check Docker Authentication
      #   run: docker info

      # - name: Push Docker image to ECR
      #   run: |
      #     docker push ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # - name: Set Up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'latest'
      
      # - name: Update kubeconfig
      #   run: |
      #     aws eks update-kubeconfig --region us-east-1 --name flask-app-cluster

      # - name: Create Kubernetes Secret
      #   run: |
      #     kubectl create secret generic capstone-secret \
      #       --from-literal=CAPSTONE_TEST=${{ secrets.CAPSTONE_TEST }} --dry-run=client -o yaml | kubectl apply -f -

      # - name: Deploy to EKS
      #   run: |
      #     kubectl apply -f deployment.yaml